version: '3.8'

services:
  beancount:
    build: .
    container_name: beancount-app
    ports:
      - "6000:6000"
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加数据库服务用于备份
  # postgres:
  #   image: postgres:15
  #   container_name: beancount-db
  #   environment:
  #     POSTGRES_DB: beancount
  #     POSTGRES_USER: beancount
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: 